data:extend({
{
  type = "item",
  name = "canned-yumako",
  icon = "__spoilage-solution__/graphics/icons/canned-yumako.png",
  icon_size = 64,
  stack_size = 10,
  spoil_ticks = 180 * minute,
  weight = 1 / 100 * tons,
  spoil_result = "spoilage",
},
{
  type = "item",
  name = "canned-jellynut",
  icon = "__spoilage-solution__/graphics/icons/canned-jellynut.png", 
  icon_size = 64,
  stack_size = 10,
  spoil_ticks = 180 * minute,
  weight = 1 / 100 * tons,
  spoil_result = "spoilage",
},
{
  type = "item",
  name = "canned-bioflux",
  icon = "__spoilage-solution__/graphics/icons/canned-bioflux.png",
  icon_size = 64,
  stack_size = 10,
  spoil_ticks = 240 * minute,
  weight = 1 / 100 * tons,
  spoil_result = "spoilage",
},
{
  type = "item",
  name = "canned-agricultural-science-pack",
  icon = "__spoilage-solution__/graphics/icons/canned-agricultural-science-pack.png",
  icon_size = 64,
  stack_size = 10,
  spoil_ticks = 240 * minute,
  weight = 1 / 100 * tons,
  spoil_result = "spoilage",
},
{
  type = "item",
  name = "frozen-yumako",
  icon = "__spoilage-solution__/graphics/icons/canned-yumako.png",
  icon_size = 64,
  stack_size = 25,
  spoil_ticks = 60 * 10000 * minute,
  weight = 1 / 500 * tons,
  spoil_result = "spoilage",
},
{
  type = "item",
  name = "frozen-jellynut",
  icon = "__spoilage-solution__/graphics/icons/canned-jellynut.png", 
  icon_size = 64,
  stack_size = 25,
  spoil_ticks = 60 * 10000 * minute,
  weight = 1 / 500 * tons,
  spoil_result = "spoilage",
},
{
  type = "item",
  name = "frozen-bioflux",
  icon = "__spoilage-solution__/graphics/icons/canned-jellynut.png",
  icon_size = 64,
  stack_size = 50,
  spoil_ticks = 60 * 10000 * minute,
  weight = 1 / 500 * tons,
  spoil_result = "spoilage",
},
{
  type = "item",
  name = "frozen-agricultural-science-pack",
  icon = "__spoilage-solution__/graphics/icons/canned-agricultural-science-pack.png",
  icon_size = 64,
  stack_size = 100,
  spoil_ticks = 60 * 10000 * minute,
  weight = 1 / 500 * tons,
  spoil_result = "spoilage",
}
,
{
  type = "item",
  name = "frozen-biter-egg",
  icon = "__spoilage-solution__/graphics/icons/canned-agricultural-science-pack.png",
  icon_size = 64,
  stack_size = 100,
  spoil_ticks = 60 * 10000 * minute,
  weight = 1 / 500 * tons,
  spoil_result = "spoilage",
}
,
{
  type = "item",
  name = "frozen-pentapod-egg",
  icon = "__spoilage-solution__/graphics/icons/canned-agricultural-science-pack.png",
  icon_size = 64,
  stack_size = 100,
  spoil_ticks = 60 * 10000 * minute,
  weight = 1 / 500 * tons,
  spoil_result = "spoilage",
}
})